Traceback (most recent call last):
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.model_selection import GridSearchCV

params = {'max_leaf_nodes': list(range(2, 100)), 'min_samples_split': [2, 3, 4]}
grid_search_cv = GridSearchCV(DecisionTreeClassifier(random_state=42), params, verbose=1, cv=3)

grid_search_cv.fit(X_train, y_train)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [3][0m, in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmodel_selection[39;00m [38;5;28;01mimport[39;00m GridSearchCV
[0;32m      3[0m params [38;5;241m=[39m {[38;5;124m'[39m[38;5;124mmax_leaf_nodes[39m[38;5;124m'[39m: [38;5;28mlist[39m([38;5;28mrange[39m([38;5;241m2[39m, [38;5;241m100[39m)), [38;5;124m'[39m[38;5;124mmin_samples_split[39m[38;5;124m'[39m: [[38;5;241m2[39m, [38;5;241m3[39m, [38;5;241m4[39m]}
[1;32m----> 4[0m grid_search_cv [38;5;241m=[39m GridSearchCV([43mDecisionTreeClassifier[49m(random_state[38;5;241m=[39m[38;5;241m42[39m), params, verbose[38;5;241m=[39m[38;5;241m1[39m, cv[38;5;241m=[39m[38;5;241m3[39m)
[0;32m      6[0m grid_search_cv[38;5;241m.[39mfit(X_train, y_train)

[1;31mNameError[0m: name 'DecisionTreeClassifier' is not defined
NameError: name 'DecisionTreeClassifier' is not defined

